# Generated by Django 4.2.10 on 2024-06-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_survey_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='respondent_identifier',
            field=models.CharField(default=0, max_length=36),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('survey_question', 'respondent_identifier')},
        ),
        migrations.RemoveField(
            model_name='response',
            name='respondent_hash',
        ),
    ]
